name: reviewdog

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
jobs:
  Setup:
    if: github.event.pull_request.draft == false
    name: install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: bahmutov/npm-install@v1

      - name: Run lint
        run: npm run lint

  # ESlint:
  #   if: github.event.pull_request.draft == false
  #   name: eslint
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [Setup]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: ESlint
  #       uses: reviewdog/action-eslint@v1
  #       with:
  #         reporter: github-pr-review
  #         level: error
  #         filter_mode: nofilter
  #         fail_on_error: true
  #         eslint_flags: '--quiet --ignore-path .gitignore .'
